version: '3.8'

services:

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts        # Monte ton dossier contenant le script test.js
    working_dir: /scripts
    entrypoint: [""]
    command: >
      sh -c "k6 run test.js"
