global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'backend-javascript'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - host.docker.internal:3001

  - job_name: 'backend-typescript'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - host.docker.internal:3002

  - job_name: 'backend-springboot'
    metrics_path: '/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:3003
