version: '3.8'

services:
  backend:
    build:
      context: .
    image: backend-typescript
    container_name: backend-typescript-container
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: npm run start
