version: '3.8'

services:
  backend:
    build:
      context: .
    image: backend-javascript-cjs
    container_name: backend-javascript-cjs-container
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    command: npm run start
