services:
  backend:
    build:
      context: .
    image: backend-javascript
    container_name: backend-javascript-container
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: npm run start
